version: 2
jobs:
  DevelopmentEnvironment:
    docker:
      - image: circleci/node:8.10
    steps:
      - add_ssh_keys:
         fingerprints:
           - "a0:10:07:ed:9d:01:87:51:ea:45:05:1d:19:1f:90:70"
      - checkout
      - run:
         name: "Archivo yaml" 
         command: |
           cd ./Configuracion
           scp -o StrictHostKeyChecking=no -r ./* ec2-user@3.235.152.80:~/
           ssh -o StrictHostKeyChecking=no ec2-user@3.235.152.80 "kubectl delete all --all"
           ssh -o StrictHostKeyChecking=no ec2-user@3.235.152.80 "kubectl delete all --all"
           ssh -o StrictHostKeyChecking=no ec2-user@3.235.152.80 "kubectl apply -f deployment.yaml"
  ProductionEnvironment:
    docker:
      - image: circleci/node:8.10
    steps:
      - add_ssh_keys:
         fingerprints:
           - "a0:10:07:ed:9d:01:87:51:ea:45:05:1d:19:1f:90:70"
      - checkout
      - run:
         name: "Archivo yaml" 
         command: |
           cd ./Configuracion
           scp -o StrictHostKeyChecking=no -r ./* ec2-user@3.94.81.164:~/
           ssh -o StrictHostKeyChecking=no ec2-user@3.94.81.164 "kubectl delete all --all"
           ssh -o StrictHostKeyChecking=no ec2-user@3.94.81.164 "kubectl delete all --all"
           ssh -o StrictHostKeyChecking=no ec2-user@3.94.81.164 "kubectl apply -f deployment.yaml"
workflows:
  version: 2
  build: 
    jobs:
      - DevelopmentEnvironment
      - request-testing:
          type: approval
          requires:
            - DevelopmentEnvironment
      - ProductionEnvironment:
          requires:
            - request-testing
